### ISSUE TITLE
  ValueError: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by GOATGAMER07** [diffus-me/sd-webui-facefusion#21]
Error executing callback ui_tabs_callback for D:\Personal\webui_forge_cu121_torch21\webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py
    Traceback (most recent call last):
      File "D:\Personal\webui_forge_cu121_torch21\webui\modules\script_callbacks.py", line 169, in ui_tabs_callback
        res += c.callback() or []
      File "D:\Personal\webui_forge_cu121_torch21\webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py", line 12, in on_ui_tabs
        apply_args(get_argument_parser())
      File "D:\Personal\webui_forge_cu121_torch21\webui\extensions\sd-webui-facefusion\facefusion\core.py", line 27, in get_argument_parser
        signal.signal(signal.SIGINT, lambda signal_number, frame: destroy())
      File "signal.py", line 56, in signal
    ValueError: signal only works in main thread of the main interpreter

**Comment by linjiX** [comment]
Fixed in  a901644cb7c74e1c37a25bb0796adad7b168bf42
