### ISSUE TITLE
    ModuleNotFoundError: No module named 'onnxruntime'

### ISSUE THREAD

**Issue by elen07zz** [diffus-me/sd-webui-facefusion#8]
Error tryting to install this extension:
ModuleNotFoundError: No module named 'onnxruntime'

`venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Collecting protobuf<=3.9999,>=3.20
  Using cached protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.0
    Uninstalling protobuf-4.25.0:
      Successfully uninstalled protobuf-4.25.0
Successfully installed protobuf-3.20.3
D:\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension D:\stable-diffusion-webui\extensions\sd-webui-facefusion.
*** Command: "D:\stable-diffusion-webui\venv\Scripts\python.exe" "D:\stable-diffusion-webui\extensions\sd-webui-facefusion\install.py"
*** Error code: 1
*** stdout: Installing None
***
*** stderr: Traceback (most recent call last):
***   File "D:\stable-diffusion-webui\extensions\sd-webui-facefusion\install.py", line 26, in <module>
***     launch.run_pip("install 'onnxruntime-gpu>=1.16.0'")
***   File "D:\stable-diffusion-webui\modules\launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "D:\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install None.
*** Command: "D:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install 'onnxruntime-gpu>=1.16.0' --prefer-binary
*** Error code: 1
*** stderr: ERROR: Invalid requirement: "'onnxruntime-gpu"
***
*** [notice] A new release of pip available: 22.2.1 -> 23.3.1
*** [notice] To update, run: D:\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
***
Launching Web UI with arguments: --precision autocast --opt-split-attention --xformers
Civitai Helper: Get Custom Model Folder
[-] ADetailer initialized. version: 23.10.1, num models: 13
2023-11-02 16:23:34,517 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-11-02 16:23:34,588 - ControlNet - INFO - ControlNet v1.1.411
*** Error loading script: facefusion_ui.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py", line 6, in <module>
        from facefusion.core import apply_args, get_argument_parser, limit_resources, pre_check
      File "D:\stable-diffusion-webui\extensions\sd-webui-facefusion\facefusion\core.py", line 11, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'`

**Comment by linjiX** [comment]
Fixed in 282165a789cfe354e5f9d4661e24fa10e68592b8, please pull the latest code and try again.
